#!/bin/bash -

db2 connect to $1 user $2 using $3

db2 bind $41A105Jdkmk.bnd
db2 bind $41A105bunchu.bnd
db2 bind $41A105irai.bnd
db2 bind $41A105kjnmst.bnd
db2 bind $41A105kmkmst.bnd
db2 bind $41A105knja.bnd
db2 bind $41A105knsgmst.bnd
db2 bind $41A105korder.bnd
db2 bind $41A105krkmk.bnd
db2 bind $41A105ninsiki.bnd
db2 bind $41A105realchk.bnd
db2 bind $41A105rngchk.bnd
db2 bind $41A105sknchk.bnd
db2 bind $41A105syskan.bnd
db2 bind $41A105wsseq.bnd
db2 bind $41A105zoku.bnd
db2 bind $41A105cntBunchu.bnd

db2 terminate

